paradedb/pg_analytics

README.md, src/fdw/trigger.rs, tests/scan.rs, tests/table_config.rs
- Closes #
Moves the following recent commits into this repo:
https://github.com/paradedb/paradedb/commit/8c567e971441d3dea3e6b4d6cf36dc3bbf503eca
https://github.com/paradedb/paradedb/commit/1a7d45fe904a23c8842d559ebdcff4a9bef5a9f7
https://github.com/paradedb/paradedb/commit/6e6d766e5bade0e33ff344291f22095c964cbdc9
https://github.com/paradedb/paradedb/commit/e285210c255e25b3e69f399ff9b2da2edb233c9c
=> chore: Migrate changes from monorepo

Cargo.toml, src/lib.rs, src/schema/cell.rs, tests/scan.rs
Reverts paradedb/pg_analytics#34. It did not pass tests, the tests were simply not running
=> Revert "fix: Fixes datetime functions support"

Cargo.toml
=> chore: Add latest wrappers commit

Cargo.toml, pg_analytics.control
- Closes #
We were setting the version in the wrong file, so it was still 0.8.6.
=> chore: Fix the version setting

.cargo/config.toml
- Closes #N/A
This fixes a bug with `pg_analytics` not working on M1.
=> fix: Rm cpu=native

.cargo/config.toml, Cargo.toml, pg_analytics.control
=> feat: Prod Promotion - v0.1.0

src/lib.rs
=> chore: Rename to PgAnalytics

src/lib.rs
- Closes #
Fixes a deployment issue, we can reactivate later once we have more tests.
=> fix: Comment out telemetry

.github/workflows/lint-cargo-toml.yml, .pre-commit-config.yaml, Cargo.toml
Follow up https://github.com/paradedb/paradedb/pull/1555
=> chore: Add toml formatting check

src/fdw/base.rs, tests/scan.rs
- Closes # https://github.com/paradedb/pg_analytics/issues/47
=> feat: pushdown quals to duckdb in fdw

Cargo.toml, sql/pg_analytics--0.1.0--0.1.1.sql
=> chore: Prepare v0.1.1

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-github-release.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml, Cargo.toml, README.md, sql/pg_analytics--0.1.0--0.1.1.sql, src/api/time_bucket.rs, src/bin/pgrx_embed.rs, src/duckdb/connection.rs, src/duckdb/mod.rs, src/duckdb/spatial.rs, src/fdw/base.rs, src/fdw/handler.rs, src/fdw/mod.rs, src/fdw/spatial.rs, src/fdw/trigger.rs, src/hooks/executor.rs, src/hooks/mod.rs, src/hooks/query.rs, src/lib.rs, tests/fixtures/arrow.rs, tests/fixtures/mod.rs, tests/scan.rs, tests/spatial.rs
- Closes #N/A
This promotes v0.1.1, which will be the first tagged version of `pg_analytics` since the repository separation.
^
^
^
=> feat: Prod Promotion -- v0.1.1

.github/workflows/publish-github-release.yml
- Closes #
We missed a place to update to the new repo, which meant the release version wasn't being triggered properly
=> fix: Fix release versioning

.github/workflows/publish-github-release.yml
- Closes #
Hotfix to the v0.1.2 deployment flow
=> feat: Prod Promotion -- v0.1.2

.github/workflows/test-pg_analytics.yml
- Closes #N/A
Not required and was slowing down CI
^
^
^
=> ci: Rm cargo clean

Cargo.lock, Cargo.toml, sql/pg_analytics--0.1.2--0.1.3.sql
=> chore: Prep v0.1.3

Cargo.lock, Cargo.toml, sql/pg_analytics--0.1.3--0.1.4.sql
=> chore: Prep v0.1.4 upgrade

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml, Cargo.lock, Cargo.toml, README.md, sql/pg_analytics--0.1.3--0.1.4.sql
- Closes #N/A
Upgrade to pgrx `0.12.4`
^
^
^
=> feat: Prod Promotion -- v0.1.4

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml
- Follow https://github.com/paradedb/paradedb/pull/1655
=> feat: Dynamically determine pgrx version in CI / Docker

Cargo.lock, Cargo.toml, src/hooks/executor.rs, src/hooks/mod.rs, src/hooks/query.rs, src/hooks/utility.rs, tests/explain.rs
=> feat: implement basic `EXPLAIN` statement

README.md, src/duckdb/connection.rs, src/duckdb/json.rs, src/duckdb/mod.rs, src/fdw/base.rs, src/fdw/json.rs, src/fdw/mod.rs
- Closes https://github.com/paradedb/pg_analytics/issues/94
FDW to read JSON files
See issue
Follow implementation of CSV FDW, use `read_json` function of DuckDB
Unit tests for generating `CREATE VIEW` statement
=> feat: Json fdw

Cargo.lock, Cargo.toml, README.md
=> chore: Update pgrx to 0.12.5

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml, Cargo.lock, Cargo.toml, README.md, src/hooks/query.rs
=> feat: Add support for PG17

.codespellignore, .github/workflows/check-typo.yml, CONTRIBUTING.md, tests/fixtures/arrow.rs
- Follow https://github.com/paradedb/paradedb/pull/1725
=> feat: Add GitHub Actions Workflow to check for typos

.github/workflows/check-pg_analytics-schema-upgrade.yml
=> chore: Update schema upgrade comment instead of overwriting

Cargo.lock, Cargo.toml, README.md
- Closes #N/A
Upgrade pgrx!
^
^
^
=> chore: Upgrade pgrx

Cargo.lock, Cargo.toml, sql/pg_analytics--0.2.0--0.2.1.sql
=> chore: Prepare 0.2.1

.github/workflows/assign-github-issue.yml, .github/workflows/benchmark-pg_analytics.yml, .github/workflows/check-pg_analytics-schema-upgrade.yml, .github/workflows/check-typo.yml, .github/workflows/lint-format.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-pr-title.yml, .github/workflows/lint-rust.yml, .github/workflows/lint-yaml.yml, .github/workflows/publish-github-release.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml, CODE_OF_CONDUCT.md
- Closes #N/a
Moving our runners to Ubicloud
Cheaper
Change tag
CI
=> chore: Move to Ubicloud

.github/workflows/publish-pg_analytics.yml
=> chore: Don't publish for PG13

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml
=> chore: Add cache to benchmark CI

tests/tests/fixtures/db.rs
=> docs: Update paradedb/paradedb folder structure

Cargo.lock, Cargo.toml, README.md, sql/pg_analytics--0.2.2--0.2.3.sql, tests/Cargo.toml
=> feat: Prod Promotion -- v0.2.3

.github/workflows/check-pg_analytics-schema-upgrade.yml, Cargo.lock, Cargo.toml, README.md, docs/object_stores/huggingface.mdx, sql/pg_analytics--0.2.3--0.2.4.sql, src/duckdb/connection.rs, src/duckdb/json.rs, src/hooks/utility.rs, src/hooks/utility/explain.rs, tests/Cargo.toml, tests/tests/explain.rs, tests/tests/fixtures/arrow.rs, tests/tests/table_config.rs
=> feat: Prod Promotion -- v0.2.4

src/api/duckdb.rs, tests/tests/settings.rs
- Closes #186 
Enhanced debugging capabilities. 
add a duckdb_extensions() shows duckdb extension details.
=> feat: add a duckdb_extensions() shows duckdb extension details

Cargo.lock, Cargo.toml, sql/pg_analytics--0.2.4--0.3.0.sql, tests/Cargo.toml
=> chore: Prep 0.3.0

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/test-pg_analytics.yml
=> ci: Make CI equivalent to `paradedb/paradedb`

Cargo.lock, Cargo.toml, sql/pg_analytics--0.3.1--0.3.2.sql, tests/Cargo.toml
=> chore: Upgrade to 0.3.2

Cargo.lock, Cargo.toml, META.json.in, pg_analytics.control, sql/pg_analytics--0.3.3--0.3.4.sql, src/duckdb/connection.rs, tests/Cargo.toml
=> feat: Prod Promotion -- v0.3.4

Cargo.lock, Cargo.toml, src/fdw/trigger.rs, tests/Cargo.toml
=> chore: upgrade to pgrx v0.13.0

Cargo.lock, Cargo.toml, sql/pg_analytics--0.3.4--0.3.5.sql, src/fdw/trigger.rs, tests/Cargo.toml
=> feat: Prod Promotion -- v0.3.5

.github/workflows/check-pg_analytics-schema-upgrade.yml, .github/workflows/publish-pg_analytics-debian.yml, .github/workflows/publish-pg_analytics-ubuntu.yml, .github/workflows/test-pg_analytics-upgrade.yml, .github/workflows/test-pg_analytics.yml
- Closes #N/A
Final release.
^
^
^
=> feat: Prod Promotion -- v0.3.6
