paradedb/pg_analytics

- .pre-commit-config.yaml
- Closes #
Copy `.pre-commit-config.yaml` from the paradedb https://github.com/paradedb/paradedb/blob/dev/.pre-commit-config.yaml, but remove the`mintlify-validate` because it seems that we do not maintain doc in the repo
> chore: Update pre-commit hooks and dependencies

- .github/workflows/test-pg_analytics.yml
- Closes #60
This was not properly configured since moving to the new repo, and the tests weren't running!
Run tests to avoid broken code
Specify the paths properly
See CI
> chore: Make `test-pg_analytics` run in CI

- Cargo.toml
- src/lib.rs
- src/schema/cell.rs
- src/schema/datetime.rs
- tests/scan.rs
- Closes [#1371](https://github.com/paradedb/pg_analytics/issues/49)
As reported in the issue, date functions like `date_trunc`, `date_part` are not working
The `DataType::Date32` and `DataType::Date64` were not handled for `TIMESTAMPTZOID`.
Handled the case with appropriate conversions
Added a test
> fix: Fixes datetime functions support

- Cargo.toml
- src/duckdb/csv.rs
- src/duckdb/delta.rs
- src/duckdb/iceberg.rs
- src/duckdb/parquet.rs
- src/duckdb/secret.rs
- src/fdw/csv.rs
- src/fdw/delta.rs
- src/fdw/iceberg.rs
- src/fdw/parquet.rs
- Closes #82 
- Closes #83 
- Closes #84 
- Closes #80 
Added a dependency on [strum](https://docs.rs/strum/latest/strum) create to automatically provide `as_ref` & `iter` methods to enums. More can be added if needed.
The strum can be used to remove useful manual implementations
Made sure the `as_ref` & `iter` methods provide the expected output.
> chore: Automatic UserMappingOptions methods implementation

- .github/workflows/publish-github-release.yml
- .github/workflows/publish-pg_analytics.yml
- Closes #85
Publish extension binaries!
^
Moved over the original file from the monorepo.
Tested manually
> chore: Add publish CI for pg_analytics

- .github/workflows/benchmark-pg_analytics.yml
- .github/workflows/publish-pg_analytics.yml
- Closes #96
This file had been omitted when migrating the projects. This solves that. I also fix a lingering issue in the publishing script deployment.
Finish the migration
Re-added the file from the `paradedb/paradedb` repository, and made some edit to it to make it fit with the new repo.
See CI
> ci: Re-Add benchmarking Tool

- .github/workflows/benchmark-pg_analytics.yml
- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_analytics.yml
- .github/workflows/test-pg_analytics.yml
- Cargo.toml
- README.md
- src/api/time_bucket.rs
- src/bin/pgrx_embed.rs
- src/fdw/handler.rs
- src/hooks/executor.rs
- src/hooks/mod.rs
- src/hooks/query.rs
- src/lib.rs
> chore: Bump pgrx to 0.12.1

- src/duckdb/csv.rs
- src/duckdb/delta.rs
- src/duckdb/iceberg.rs
- src/duckdb/parquet.rs
- tests/table_config.rs
- Closes #
In DuckDB, it is possible to control which columns are selected or generate new columns in a view:
```sql
SELECT col1 as renamed_col, 1 as fixed FROM read_parquet('path/to/file.parquet');
```
We now expose this to the user so they can do the same when creating foreign tables. This is done via the new `select` option. (I couldn't name it `columns` because the CSV reader already has a `column`s option).
```sql
CREATE FOREIGN TABLE trips ()
SERVER parquet_server
OPTIONS (files 's3://paradedb-benchmarks/yellow_tripdata_2024-01.parquet', select 'vendorid as vendor_id, 2024 as year, 1 as month');
SELECT * FROM trips LIMIT 1;
vendor_id | year | month
-----------+------+-------
2 | 2024 |     1
(1 row)
```
This makes it possible to add generated columns to Parquet files that can be …
> feat: Support generated/renamed columns in DuckDB

- .github/workflows/lint-rust.yml
- Cargo.toml
- Closes #N/A
This was proposed by Vipul, but was never completed. I think it's a good idea, and we've already added it to the `paradedb/paradedb` repository.
Avoid unnecessary dependencies that make our binaries bigger and slower to compile.
We use `machete`
See CI
> ci: Add dependency check

- Cargo.toml
- src/duckdb/csv.rs
- src/duckdb/delta.rs
- src/duckdb/iceberg.rs
- src/duckdb/parquet.rs
- src/duckdb/secret.rs
- src/duckdb/spatial.rs
- src/fdw/base.rs
- src/fdw/csv.rs
- src/fdw/delta.rs
- src/fdw/iceberg.rs
- src/fdw/parquet.rs
- src/fdw/spatial.rs
- tests/scan.rs
- Closes https://github.com/paradedb/pg_analytics/issues/43
- introduce new `OptionValidator`
- Sanitize the user mapping in the `validator` function
> feat: Add OptionValidator trait for FDW options validation and Sanitize user mapping options

- README.md
Adds instructions on how to run the extension using pgrx 
To give clear instructions on how to use the extension for local development and make contributing easier.
Based on similar instructions for pg_search: https://github.com/paradedb/paradedb/tree/dev/pg_search#running-the-extension
N/A
> docs: add extension running instructions to readme

- Cargo.toml
- README.md
- src/hooks/query.rs
- Closes #N/A
It's getting deprecated by the PGDG since Postgres 17 is just about out. Also, we never actually supported it but it was somehow mentioned in a few places. No more PG12.
No longer supported.
Remove code!
It wasn't actually used, so...
> chore: Deprecate Postgres 12

- src/duckdb/csv.rs
- src/duckdb/delta.rs
- src/duckdb/iceberg.rs
- src/duckdb/json.rs
- src/duckdb/parquet.rs
- src/duckdb/secret.rs
- src/duckdb/spatial.rs
- Closes #
Using `#[strum(serialize_all = "snake_case")]` to avoid naming each enum.
Easy to maintain and prevent human errors.
The related tests are existing
> refactor: Use enum serialization in CSV, Delta, Iceberg, Json, Parquet, Secret, and Spatial modules

- src/duckdb/iceberg.rs
Adding support to pass option in iceberg read for metadata compression codec
It will allow users to read iceberg files for which metadata is compressed.
> fix: iceberg metadata comp codec

- src/hooks/executor.rs
- src/hooks/mod.rs
- src/hooks/query.rs
- src/hooks/utility.rs
- src/hooks/utility/explain.rs
- src/hooks/utility/prepare.rs
- tests/fixtures/arrow.rs
- tests/scan.rs
- Closes #51 
Pushdown `PREPARE`, `EXECUTE` and `DEALLOCATE` statement to duckdb directly.
> feat: support prepare pushdown

- .codespellignore
- .github/workflows/check-pg_analytics-schema-upgrade.yml
- .github/workflows/check-typo.yml
- .github/workflows/publish-pg_analytics.yml
- .github/workflows/test-pg_analytics.yml
- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- README.md
- sql/pg_analytics--0.2.0--0.2.1.sql
- src/duckdb/csv.rs
- src/duckdb/delta.rs
- src/duckdb/iceberg.rs
- src/duckdb/json.rs
- src/duckdb/parquet.rs
- src/duckdb/secret.rs
- src/duckdb/spatial.rs
- src/fdw/trigger.rs
- src/hooks/executor.rs
- src/hooks/mod.rs
- src/hooks/query.rs
- src/hooks/utility.rs
- src/hooks/utility/explain.rs
- src/hooks/utility/prepare.rs
- tests/fixtures/arrow.rs
- tests/scan.rs
> feat: Prod Promotion -- v0.2.1

- Cargo.lock
- Cargo.toml
- Closes #153 - 
support reading and writing geoparquet
with `duckdb_spatial>=v1.1.0` geometry column in parquet will be read/write as geometry instead of blob
no explicit change of sql is needed
a read/write parquet test should be added later
> chore: bump duckdb-rs version

- src/fdw/trigger.rs
- tests/tests/fixtures/arrow.rs
- tests/tests/table_config.rs
- Closes #177 
Add the option preserve_casing 'true' to ensure that reserved column names are correctly created.
add a test of creating foreign table with reserved column name
> test: add a test of creating a foreign table with reserved column name

- src/schema/cell.rs
- tests/tests/json.rs
- Closes #178 
Support Datatype::List cast to json and jsonb.
> feat: support DataType::List cast to json and jsonb

- src/hooks/utility.rs
- src/hooks/utility/view.rs
- Closes #189 
Fix misleading the warning log during initdb
Disable utility hooks during initdb. If relations do not exist in Duckdb, it shouldn't print warning logs.
> fix: Fix misleading the warning log during initdb

- Cargo.lock
- Cargo.toml
- sql/pg_analytics--0.2.4--0.3.0.sql
- src/api/duckdb.rs
- src/hooks/utility.rs
- src/hooks/utility/view.rs
- src/schema/cell.rs
- tests/Cargo.toml
- tests/tests/json.rs
- tests/tests/settings.rs
- Closes #N/A
Huge thank you to kysshsy for this one!
^
^
^
> feat: Prod Promotion -- v0.3.0

- src/duckdb/connection.rs
- src/fdw/base.rs
- Closes #
Moves loading `httpfs` and setting the extension directory to the start of the DuckDB connection so that the settings are available to the rest of the connection.
> fix: move loading `httpfs` and setting extension directory to beginning of connection

- Cargo.lock
- Cargo.toml
- sql/pg_analytics--0.3.1--0.3.2.sql
- src/duckdb/connection.rs
- src/fdw/base.rs
- tests/Cargo.toml
> feat: Prod Promotion -- v0.3.2

- .gitattributes
- .github/workflows/pgxn-release.yml
- .github/workflows/publish-pg_analytics-pgxn.yml
- META.json.in
- Makefile
Add a `Makefile` to automate populating the version in the `META.json` and creating the zip file. `.gitattributes` prevents unnecessary files from inclusion in the zip file. `.github/workflows/pgxn-release.yml` uses the `pgxn/pgxn-tools` OCI to publish the zip file on PGXN when a server tag is pushed.
To actually  publish on PGXN, you'll need to follow these steps:
1. [Request a PGXN account](https://manager.pgxn.org/account/register). I will approve it ASAP.
2. Once approved, log in and set a password.
3. Navigate to either Actions and secrets [for this repo](https://github.com/paradedb/pg_analytics/settings/secrets/actions) or, if you'd like to use the same credentials to publish other extensions on PGXN, [for the ParadeDB org](https://github.com/organizations/paradedb/settings/secrets/a …
> ci: Add PGXN META.json and release workflow

- META.json.in
- src/duckdb/connection.rs
Append `.duckdb/extensions` to the `extension_directory` to mimic DuckDB's default directory structure and so that the Postgres data directory doesn't fill up with directories starting with, e.g., `v1.1.1`, as it is not a Postgres version, so could be confusing.
Update the doc file in `META.json`, as the docs were dropped in 4934ae8.
[default directory structure]: https://duckdb.org/docs/extensions/overview.html#installation-location
> fix: Doc link and extension subdirectory
